version: '3.4'

services:
   web:
     image: nginx:alpine
     container_name: food-api-nginx
     volumes:
       - "./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
       - "./.docker/nginx/certs:/etc/nginx/certs/api.food.test/"
     ports:
       - "80:80"
       - "443:443"
     command: nginx -g 'daemon off;'
     restart: always
     links:
       - "app"
     depends_on:
       - app

   app:
     build:
       context: .
       dockerfile: Dockerfile
       target: prod
     restart: always
     image: food-api
     container_name: food-api
     volumes:
       - "./data/media:/data/media"
     env_file:
       - .env
     ports:
       - "5000:80"
     links:
       - "db"
     depends_on:
       - db

   db:
     image: "mysql:5.7.21"
     container_name: food-api-mysql
     restart: always
     env_file:
      - .env
     volumes:
      - ./.docker/mysql/:/docker-entrypoint-initdb.d/
      - ./data/mysql:/var/lib/mysql
     ports:
        - "3310:3306"

